version: 2.1

references:

# Set working directory
working_directory: &working_directory ~/project

# Set default configuration
default_config: &default_config
  docker:
    - image: circleci/node:12-stretch
  working_directory: *working_directory

repo_cache_key: &repo_cache_key v1-repo-{{ .Branch }}-{{ .Revision }}

# Step to save repository from cache
save_repo: &save_repo
  save_cache:
    key: *repo_cache_key
    paths:
      - *working_directory

restore_repo: &restore_repo
  restore_cache:
    key: *repo_cache_key

jobs:
  before_script:
    <<: *default_config
    steps:
      - checkout
      - run:
          name: npm clean install
          command: npm ci
      - *save_repo

  check:
    <<: *default_config
    steps:
      - *restore_repo
      - run:
          name: format
          command: npm run check-format
      - run:
          name: lint
          command: npm run lint

  test:
    <<: *default_config
    steps:
      - *restore_repo
      - run:
          name: npm test
          command: |
            npm test

  publish:
    <<: *default_config
    steps:
      - *restore_repo
      - run:
          name: authenticate
          command: |
            echo //registry.npmjs.org/:_authToken=${CAZOO_NPM_TOKEN}>.npmrc
      - run:
            name: Publish package
            command: npm publish

workflows:
  release:
    jobs:
      - before_script:
          name: "Init"
          filters:
            tags:
              only: /^v.*/
      - check:
          name: "Linting"
          filters:
            tags:
              only: /^v.*/
          requires:
            - "Init"
      - test:
          name: "Run tests"
          requires:
            - "Linting"
          filters:
            tags:
              only: /^v.*/
      - publish:
          name: "Publish package"
          requires:
            - "Run tests"
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/          
